/* AUTO-GENERATED BY bash/transak.sankey.sh */
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-12-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202512`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-11-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202511`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-10-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202510`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-09-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202509`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-08-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202508`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-07-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202507`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-06-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202506`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-05-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202505`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-04-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202504`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-03-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202503`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-02-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202502`
UNION ALL
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('2025-01-01' AS DATE) AS month
FROM `af-finanzen.monatsabschluss.sankey_202501`
