#!/bin/bash

# Resolve the absolute path of the script directory (resolves symlinks)
# This requires 'realpath' (standard in Ubuntu/WSL)
SCRIPT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

# Optional argument: Specific Month (YYYYMM)
FILTER_MONTH="$1"
# Optional argument: SQL Only Flag (sql-only)
SQL_ONLY_FLAG="$2"

# --- Configuration ---
PROJECT_ID="af-finanzen"
DATASET_ID="monatsabschluss"
TABLE_INFO_FILE="transak.monatsabschluss.csv" # Uses the same CSV input
OUTPUT_TABLE_PREFIX="sankey_" # Prefix for the new tables

# Schema source JSON file
SCHEMA_JSON_FILE_PATH="$SCRIPT_DIR/../terraform/bq-schemas/monatsabschluss.sankey.json"

# Fixed Google Sheet details
FIXED_SHEET_RANGE="Sankey!A:D"
FIXED_SKIP_ROWS=1

# --- Helper function to check for jq ---
check_jq() {
    if ! command -v jq &> /dev/null
    then
        echo "Error: jq is not installed. Please install jq to proceed." >&2
        exit 1
    fi
}

# --- Main Script ---

# 1. Check for jq
check_jq

# 2. Prepare the schema from the JSON file
echo "Preparing schema definition from $SCHEMA_JSON_FILE_PATH..." >&2
if [ ! -f "$SCHEMA_JSON_FILE_PATH" ]; then
    echo "Error: Schema JSON file '$SCHEMA_JSON_FILE_PATH' not found." >&2
    exit 1
fi

SCHEMA_FIELDS_AS_JSON_ARRAY=$(jq -c '.' "$SCHEMA_JSON_FILE_PATH")

if [ -z "$SCHEMA_FIELDS_AS_JSON_ARRAY" ] || [ "$SCHEMA_FIELDS_AS_JSON_ARRAY" == "null" ] || [ "$SCHEMA_FIELDS_AS_JSON_ARRAY" == "[]" ]; then
    echo "Error: Could not read, parse, or schema is empty in $SCHEMA_JSON_FILE_PATH." >&2
    exit 1
fi
echo "Schema definition prepared successfully." >&2
echo "---" >&2

# 3. Check if the table info file exists
if [ ! -f "$TABLE_INFO_FILE" ]; then
    echo "Error: Table info file '$TABLE_INFO_FILE' not found." >&2
    exit 1
fi

# 4. Loop through the CSV and recreate tables
if [[ "$SQL_ONLY_FLAG" == "sql-only" || "$SQL_ONLY_FLAG" == "--sql-only" ]]; then
    echo "Skipping table creation (sql-only mode)." >&2
else
    while IFS=, read -r old_table_name gsheet_url || [[ -n "$old_table_name" ]];
    do
        # Trim whitespace
        old_table_name=$(echo "$old_table_name" | xargs)
        gsheet_url=$(echo "$gsheet_url" | xargs)

        if [ -z "$old_table_name" ] || [ -z "$gsheet_url" ]; then
            continue
        fi

        # Extract suffix (e.g. 202512 from revolut_abrechnung_202512)
        # Assumes format: prefix_YYYYMM. We take everything after the last underscore.
        table_suffix="${old_table_name##*_}"

        # --- Filtering Logic ---
        if [ -n "$FILTER_MONTH" ]; then
            # If a specific month is provided, process ONLY that month
            if [ "$table_suffix" != "$FILTER_MONTH" ]; then
                continue
            fi
        else
            # If no month provided, process ONLY months since 202501 (inclusive)
            if [ "$table_suffix" -lt 202501 ]; then
                continue
            fi
        fi

        # Construct new table name
        new_table_name="${OUTPUT_TABLE_PREFIX}${table_suffix}"

        # FULL_TABLE_ID for messages
        LOGGING_FULL_TABLE_ID="$PROJECT_ID.$DATASET_ID.$new_table_name"
        # TABLE_ID_FOR_BQ_MK
        TABLE_ID_FOR_BQ_MK="$DATASET_ID.$new_table_name"

        echo "Processing table: $LOGGING_FULL_TABLE_ID" >&2
        echo "  Source GSheet: $gsheet_url" >&2
        echo "  Sheet Range: $FIXED_SHEET_RANGE" >&2

        # Delete the table if it exists
        # echo "  Attempting to delete table $LOGGING_FULL_TABLE_ID if it exists..." >&2
        bq rm -f -t "$TABLE_ID_FOR_BQ_MK" > /dev/null 2>&1

        # Create the external table definition file
        DEF_FILE_PATH="temp_sankey_def_${table_suffix}.json"
        
        cat <<EOF > "$DEF_FILE_PATH"
{
    "sourceFormat": "GOOGLE_SHEETS",
    "sourceUris": ["$gsheet_url"],
    "schema": {
      "fields": $SCHEMA_FIELDS_AS_JSON_ARRAY
    },
    "googleSheetsOptions": {
      "range": "$FIXED_SHEET_RANGE",
      "skipLeadingRows": $FIXED_SKIP_ROWS
    },
    "ignoreUnknownValues": false
}
EOF

        if [ ! -s "$DEF_FILE_PATH" ]; then
            echo "Error: Failed to create definition file: $DEF_FILE_PATH" >&2
            continue
        fi

        echo "  Creating table $new_table_name..." >&2
        bq mk --table --location=europe-west6 --external_table_definition="$DEF_FILE_PATH" "$TABLE_ID_FOR_BQ_MK"

        if [ $? -eq 0 ]; then
            echo "  -> Success: $new_table_name" >&2
        else
            echo "  -> Error: Failed to create $new_table_name" >&2
        fi

        # Clean up
        rm -f "$DEF_FILE_PATH"

    done < "$TABLE_INFO_FILE"
fi

echo "All Sankey tables processed." >&2
echo "-----------------------------------------------------" >&2

# --- 5. Generate Union View SQL ---
VIEW_FILE_PATH="$SCRIPT_DIR/../terraform/bq-views/monatsabschluss.sankey_v.sql"
echo "Generating View SQL: $VIEW_FILE_PATH" >&2

# Create/Overwrite the file
echo "/* AUTO-GENERATED BY bash/transak.sankey.sh */" > "$VIEW_FILE_PATH"

first=true

while IFS=, read -r old_table_name gsheet_url || [[ -n "$old_table_name" ]];
do
    old_table_name=$(echo "$old_table_name" | xargs)
    gsheet_url=$(echo "$gsheet_url" | xargs)

    if [ -z "$old_table_name" ] || [ -z "$gsheet_url" ]; then continue; fi

    table_suffix="${old_table_name##*_}"

    # Filter for >= 202501 for the view
    if [ "$table_suffix" -lt 202501 ]; then
        continue
    fi

    new_table_name="${OUTPUT_TABLE_PREFIX}${table_suffix}"
    
    # Construct formatting for month column (e.g., DATE(2025, 01, 01))
    # Or just as an integer/string as requested. 
    # User's error message showed: PARSE_DATE("%Y%m", _TABLE_SUFFIX)
    # We can replicate this by statically putting the date.
    
    # Extract Year and Month for PARSE_DATE or just use simple date construction
    # simpler: CAST('2025-01-01' AS DATE)
    year="${table_suffix:0:4}"
    month="${table_suffix:4:2}"
    date_str="${year}-${month}-01"

    if [ "$first" = true ]; then
        first=false
    else
        echo "UNION ALL" >> "$VIEW_FILE_PATH"
    fi

    cat <<EOF >> "$VIEW_FILE_PATH"
SELECT 
    description
  , amount
  , new_label
  , comment
  , CAST('${date_str}' AS DATE) AS month
FROM \`af-finanzen.monatsabschluss.${new_table_name}\`
EOF


done < "$TABLE_INFO_FILE"

echo "View SQL generation complete." >&2
echo "-----------------------------------------------------" >&2

# --- 6. Recreate the View in BigQuery ---
VIEW_FULL_ID="${PROJECT_ID}:${DATASET_ID}.sankey_v"
echo "Recreating BigQuery View: $VIEW_FULL_ID" >&2

# Delete existing view (if any)
bq rm -f -t "$VIEW_FULL_ID" > /dev/null 2>&1

# Read the generated SQL
VIEW_QUERY=$(cat "$VIEW_FILE_PATH")

# Create new view
# We use --use_legacy_sql=false to ensure Standard SQL
bq mk \
  --use_legacy_sql=false \
  --view "$VIEW_QUERY" \
  --project_id="$PROJECT_ID" \
  "${DATASET_ID}.sankey_v"

if [ $? -eq 0 ]; then
    echo "  -> Success: View recreated." >&2
else
    echo "  -> Error: Failed to recreate view." >&2
    exit 1
fi

echo "Script finished successfully." >&2
